__sf_config={customer_id:97311,host:'crmemails.ogilvy.com',ip_privacy:0,subsite:'',__img_path:"/web-next.gif?"};(function(){var s=function(){var e,t;var n=10;var r=0;e=document.createElement("script");e.type="text/javascript";e.async=true;e.src="//"+__sf_config.host+"/js/frs-next.js";t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t);var i=function(){if(r<n){r++;if(typeof frt!=="undefined")
{frt(__sf_config);}else{setTimeout(function()
{i();},500);}}};i();};if(window.attachEvent)
{window.attachEvent("onload",s);}else
{window.addEventListener("load",s,false);}})();;(function($,drupalSettings){Drupal.Ajax.prototype.originalBeforeSerialize=Drupal.Ajax.prototype.beforeSerialize;Drupal.Ajax.prototype.beforeSerialize=function(element,options){if(options.url&&options.url.indexOf('/views/ajax')!==-1&&drupalSettings.viewsAjaxGet&&typeof drupalSettings.viewsAjaxGet[options.data.view_name]!=='undefined'){if(this.form){var settings=this.settings||drupalSettings;Drupal.detachBehaviors(this.form,settings,'serialize');}
options.type='GET';options.url=Drupal.url('views/ajax');return;}
return this.originalBeforeSerialize(element,options);};})(jQuery,drupalSettings);;(function($,Drupal,drupalSettings){Drupal.Views={};Drupal.Views.parseQueryString=function(query){var args={};var pos=query.indexOf('?');if(pos!==-1){query=query.substring(pos+1);}
var pair=void 0;var pairs=query.split('&');for(var i=0;i<pairs.length;i++){pair=pairs[i].split('=');if(pair[0]!=='q'&&pair[1]){args[decodeURIComponent(pair[0].replace(/\+/g,' '))]=decodeURIComponent(pair[1].replace(/\+/g,' '));}}
return args;};Drupal.Views.parseViewArgs=function(href,viewPath){var returnObj={};var path=Drupal.Views.getPath(href);var viewHref=Drupal.url(viewPath).substring(drupalSettings.path.baseUrl.length);if(viewHref&&path.substring(0,viewHref.length+1)===viewHref+'/'){returnObj.view_args=decodeURIComponent(path.substring(viewHref.length+1,path.length));returnObj.view_path=path;}
return returnObj;};Drupal.Views.pathPortion=function(href){var protocol=window.location.protocol;if(href.substring(0,protocol.length)===protocol){href=href.substring(href.indexOf('/',protocol.length+2));}
return href;};Drupal.Views.getPath=function(href){href=Drupal.Views.pathPortion(href);href=href.substring(drupalSettings.path.baseUrl.length,href.length);if(href.substring(0,3)==='?q='){href=href.substring(3,href.length);}
var chars=['#','?','&'];for(var i=0;i<chars.length;i++){if(href.indexOf(chars[i])>-1){href=href.substr(0,href.indexOf(chars[i]));}}
return href;};})(jQuery,Drupal,drupalSettings);;(function($,Drupal,drupalSettings){Drupal.behaviors.ViewsAjaxView={};Drupal.behaviors.ViewsAjaxView.attach=function(context,settings){if(settings&&settings.views&&settings.views.ajaxViews){var ajaxViews=settings.views.ajaxViews;Object.keys(ajaxViews||{}).forEach(function(i){Drupal.views.instances[i]=new Drupal.views.ajaxView(ajaxViews[i]);});}};Drupal.behaviors.ViewsAjaxView.detach=function(context,settings,trigger){if(trigger==='unload'){if(settings&&settings.views&&settings.views.ajaxViews){var ajaxViews=settings.views.ajaxViews;Object.keys(ajaxViews||{}).forEach(function(i){var selector='.js-view-dom-id-'+ajaxViews[i].view_dom_id;if($(selector,context).length){delete Drupal.views.instances[i];delete settings.views.ajaxViews[i];}});}}};Drupal.views={};Drupal.views.instances={};Drupal.views.ajaxView=function(settings){var selector='.js-view-dom-id-'+settings.view_dom_id;this.$view=$(selector);var ajaxPath=drupalSettings.views.ajax_path;if(ajaxPath.constructor.toString().indexOf('Array')!==-1){ajaxPath=ajaxPath[0];}
var queryString=window.location.search||'';if(queryString!==''){queryString=queryString.slice(1).replace(/q=[^&]+&?|&?render=[^&]+/,'');if(queryString!==''){queryString=(/\?/.test(ajaxPath)?'&':'?')+queryString;}}
this.element_settings={url:ajaxPath+queryString,submit:settings,setClick:true,event:'click',selector:selector,progress:{type:'fullscreen'}};this.settings=settings;this.$exposed_form=$('form#views-exposed-form-'+settings.view_name.replace(/_/g,'-')+'-'+settings.view_display_id.replace(/_/g,'-'));this.$exposed_form.once('exposed-form').each($.proxy(this.attachExposedFormAjax,this));this.$view.filter($.proxy(this.filterNestedViews,this)).once('ajax-pager').each($.proxy(this.attachPagerAjax,this));var selfSettings=$.extend({},this.element_settings,{event:'RefreshView',base:this.selector,element:this.$view.get(0)});this.refreshViewAjax=Drupal.ajax(selfSettings);};Drupal.views.ajaxView.prototype.attachExposedFormAjax=function(){var that=this;this.exposedFormAjax=[];$('input[type=submit], input[type=image]',this.$exposed_form).not('[data-drupal-selector=edit-reset]').each(function(index){var selfSettings=$.extend({},that.element_settings,{base:$(this).attr('id'),element:this});that.exposedFormAjax[index]=Drupal.ajax(selfSettings);});};Drupal.views.ajaxView.prototype.filterNestedViews=function(){return!this.$view.parents('.view').length;};Drupal.views.ajaxView.prototype.attachPagerAjax=function(){this.$view.find('ul.js-pager__items > li > a, th.views-field a, .attachment .views-summary a').each($.proxy(this.attachPagerLinkAjax,this));};Drupal.views.ajaxView.prototype.attachPagerLinkAjax=function(id,link){var $link=$(link);var viewData={};var href=$link.attr('href');$.extend(viewData,this.settings,Drupal.Views.parseQueryString(href),Drupal.Views.parseViewArgs(href,this.settings.view_base_path));var selfSettings=$.extend({},this.element_settings,{submit:viewData,base:false,element:link});this.pagerAjax=Drupal.ajax(selfSettings);};Drupal.AjaxCommands.prototype.viewsScrollTop=function(ajax,response){var offset=$(response.selector).offset();var scrollTarget=response.selector;while($(scrollTarget).scrollTop()===0&&$(scrollTarget).parent()){scrollTarget=$(scrollTarget).parent();}
if(offset.top-10<$(scrollTarget).scrollTop()){$(scrollTarget).animate({scrollTop:offset.top-10},500);}};})(jQuery,Drupal,drupalSettings);;window.matchMedia||(window.matchMedia=function(){"use strict";var e=window.styleMedia||window.media;if(!e){var t=document.createElement("style"),i=document.getElementsByTagName("script")[0],n=null;t.type="text/css";t.id="matchmediajs-test";i.parentNode.insertBefore(t,i);n="getComputedStyle"in window&&window.getComputedStyle(t,null)||t.currentStyle;e={matchMedium:function(e){var i="@media "+e+"{ #matchmediajs-test { width: 1px; } }";if(t.styleSheet){t.styleSheet.cssText=i}else{t.textContent=i}return n.width==="1px"}}}return function(t){return{matches:e.matchMedium(t||"all"),media:t||"all"}}}());;(function($,Drupal,drupalSettings){Drupal.behaviors.betterExposedFilters={attach:function(context,settings){$('.bef-tree input[type=checkbox], .bef-checkboxes input[type=checkbox]').change(function(){_bef_highlight(this,context);}).filter(':checked').closest('.form-item',context).addClass('highlight');}};function _bef_highlight(elem,context){$elem=$(elem,context);$elem.attr('checked')?$elem.closest('.form-item',context).addClass('highlight'):$elem.closest('.form-item',context).removeClass('highlight');}})(jQuery,Drupal,drupalSettings);;(function($,Drupal){Drupal.behaviors.betterExposedFiltersAutoSubmit={attach:function(context){var selectors='form[data-bef-auto-submit-full-form], [data-bef-auto-submit-full-form] form, [data-bef-auto-submit]';$(selectors,context).addBack(selectors).each(function(i,e){var $form=$(e);var autoSubmitDelay=$form.data('bef-auto-submit-delay')||500;$form.once('bef-auto-submit').on('change',triggerSubmit).on('keyup',Drupal.debounce(triggerSubmit,autoSubmitDelay));});function triggerSubmit(e){var ignoredKeyCodes=[16,17,18,20,33,34,35,36,37,38,39,40,9,13,27];var $target=$(e.target);var $submit=$target.closest('form').find('[data-bef-auto-submit-click]');if($target.is('[data-bef-auto-submit-exclude], :submit')){return true;}
if($target.is(':text:not(.hasDatepicker), textarea')&&$.inArray(e.keyCode,ignoredKeyCodes)===-1){$submit.click();}
else if(e.type==='change'){$submit.click();}}}}}(jQuery,Drupal));;(function($){Drupal.behaviors.betterExposedFiltersSelectAllNone={attach:function(context){var selected=$('.form-checkboxes.bef-select-all-none:not(.bef-processed)');if(selected.length){var selAll=Drupal.t('Select All');var selNone=Drupal.t('Select None');var link=$('<a class="bef-toggle" href="#">'+selAll+'</a>')
link.click(function(event){event.preventDefault();event.stopPropagation();if(selAll==$(this).text()){$(this).html(selNone).siblings('.bef-select-all-none, .bef-tree').find('input:checkbox').each(function(){$(this).prop('checked',true);}).end().find('input[type=checkbox]:first').change();}
else{$(this).html(selAll).siblings('.bef-select-all-none, .bef-tree').find('input:checkbox').each(function(){$(this).prop('checked',false);}).end().find('input[type=checkbox]:first').change();}});selected.addClass('bef-processed').each(function(index){var newLink=link.clone(true);newLink.insertBefore($(this));if($('input:checkbox:checked',this).length==$('input:checkbox',this).length){newLink.text(selNone);}});}}};Drupal.behaviors.betterExposedFiltersAllNoneNested={attach:function(context,settings){$('.bef-select-all-none-nested li').has('ul').once('bef-all-none-nested').each(function(){var $this=$(this);$this.find('input:checkbox:first').change(function(){$(this).closest('li').find('ul li input:checkbox').prop('checked',this.checked);});$this.find('ul input:checkbox').change(function(){var $this=$(this);var uncheckedSiblings=$this.closest('li').siblings('li').find('> div > input:checkbox:not(:checked)').length;if(uncheckedSiblings||!this.checked){$this.parents('ul').siblings('div').find('input:checkbox').prop('checked',false);}
if(this.checked&&!uncheckedSiblings){$(this).closest('ul').closest('li').find('input:checkbox:first').prop('checked',true).change();}});});}}})(jQuery);;